name: push-main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "main"

jobs:
  build-test-runcodecoverage:
    uses: ./.github/workflows/build_test_react.yml

  push-image:
    needs: build-test-runcodecoverage
    env:
      IMAGE: davebosleyhpe/glpoc
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of docker images
        images: |
          davebosleyhpe/glpoc
        # generate Docker tags based on following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
      
     # These are prerequisites for the docker build step
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and publish container image with tags
      uses: docker/build-push-action@v4    
      with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          #              ${{ env.IMAGE }}:${{ github.run_number }}-${{ github.sha }}
